Updates to compile on CRAN
The initial submission returned installation errors
like the following:
tsne.o:tsne.c:(.text+0x15a): undefined reference to `dgemm_'

Added #include <R_ext/BLAS.h> to preamble,
created Makevars & Makevars.win based on the
RcppArmadillo package, and specified GNU make
in the DESCRIPTION.